// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: unused_field, type=lint, unused_import
import 'dart:ffi' as ffi;

@ffi.Native<ma_device_config Function(ffi.UnsignedInt)>()
external ma_device_config ma_device_config_init(int deviceType);

@ffi.Native<
  ffi.UnsignedInt Function(
    ffi.Pointer<ma_context>,
    ffi.Pointer<ma_device_config>,
    ffi.Pointer<ma_device>,
  )
>()
external int ma_device_init(
  ffi.Pointer<ma_context> pContext,
  ffi.Pointer<ma_device_config> pConfig,
  ffi.Pointer<ma_device> pDevice,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ma_device>)>()
external void ma_device_uninit(ffi.Pointer<ma_device> pDevice);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ma_device>)>()
external int ma_device_start(ffi.Pointer<ma_device> pDevice);

@ffi.Native<ffi.UnsignedInt Function(ffi.Pointer<ma_device>)>()
external int ma_device_stop(ffi.Pointer<ma_device> pDevice);

final class _opaque_pthread_cond_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([40])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_mutex_t extends ffi.Struct {
  @ffi.Long()
  external int __sig;

  @ffi.Array.multi([56])
  external ffi.Array<ffi.Char> __opaque;
}

final class _opaque_pthread_t extends ffi.Opaque {}

final class ma_context extends ffi.Opaque {}

final class ma_atomic_device_state extends ffi.Struct {
  @ffi.UnsignedInt()
  external int value;
}

typedef ma_device_data_procFunction =
    ffi.Void Function(
      ffi.Pointer<ma_device> pDevice,
      ffi.Pointer<ffi.Void> pOutput,
      ffi.Pointer<ffi.Void> pInput,
      ffi.UnsignedInt frameCount,
    );
typedef Dartma_device_data_procFunction =
    void Function(
      ffi.Pointer<ma_device> pDevice,
      ffi.Pointer<ffi.Void> pOutput,
      ffi.Pointer<ffi.Void> pInput,
      int frameCount,
    );
typedef ma_device_data_proc =
    ffi.Pointer<ffi.NativeFunction<ma_device_data_procFunction>>;

final class ma_device_notification extends ffi.Opaque {}

final class ma_event extends ffi.Struct {
  @ffi.UnsignedInt()
  external int value;

  external _opaque_pthread_mutex_t lock;

  external _opaque_pthread_cond_t cond;
}

final class ma_atomic_float extends ffi.Struct {
  @ffi.Float()
  external double value;
}

final class ma_data_source_vtable extends ffi.Opaque {}

final class ma_data_source_base extends ffi.Struct {
  external ffi.Pointer<ma_data_source_vtable> vtable;

  @ffi.UnsignedLongLong()
  external int rangeBegInFrames;

  @ffi.UnsignedLongLong()
  external int rangeEndInFrames;

  @ffi.UnsignedLongLong()
  external int loopBegInFrames;

  @ffi.UnsignedLongLong()
  external int loopEndInFrames;

  external ffi.Pointer<ffi.Void> pCurrent;

  external ffi.Pointer<ffi.Void> pNext;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void> pDataSource)
    >
  >
  onGetNext;

  @ffi.UnsignedInt()
  external int isLooping;
}

final class ma_allocation_callbacks extends ffi.Struct {
  external ffi.Pointer<ffi.Void> pUserData;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Size sz,
        ffi.Pointer<ffi.Void> pUserData,
      )
    >
  >
  onMalloc;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Pointer<ffi.Void> Function(
        ffi.Pointer<ffi.Void> p,
        ffi.Size sz,
        ffi.Pointer<ffi.Void> pUserData,
      )
    >
  >
  onRealloc;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Void> p,
        ffi.Pointer<ffi.Void> pUserData,
      )
    >
  >
  onFree;
}

/// Ring Buffer
final class ma_rb extends ffi.Struct {
  external ffi.Pointer<ffi.Void> pBuffer;

  @ffi.UnsignedInt()
  external int subbufferSizeInBytes;

  @ffi.UnsignedInt()
  external int subbufferCount;

  @ffi.UnsignedInt()
  external int subbufferStrideInBytes;

  @ffi.UnsignedInt()
  external int encodedReadOffset;

  @ffi.UnsignedInt()
  external int encodedWriteOffset;

  @ffi.UnsignedChar()
  external int ownsBuffer;

  @ffi.UnsignedChar()
  external int clearOnWriteAcquire;

  external ma_allocation_callbacks allocationCallbacks;
}

final class ma_pcm_rb extends ffi.Struct {
  external ma_data_source_base ds;

  external ma_rb rb;

  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.UnsignedInt()
  external int sampleRate;
}

final class ma_duplex_rb extends ffi.Struct {
  external ma_pcm_rb rb;
}

final class ma_resampling_backend_vtable extends ffi.Opaque {}

final class UnnamedStruct$1 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int lpfOrder;
}

final class UnnamedStruct extends ffi.Struct {
  @ffi.UnsignedInt()
  external int algorithm;

  external ffi.Pointer<ma_resampling_backend_vtable> pBackendVTable;

  external ffi.Pointer<ffi.Void> pBackendUserData;

  external UnnamedStruct$1 linear;
}

final class UnnamedUnion extends ffi.Union {
  @ffi.Int()
  external int i;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> s;

  external ffi.Pointer<ffi.Void> p;
}

final class ma_device_id extends ffi.Union {
  @ffi.Array.multi([64])
  external ffi.Array<ffi.UnsignedShort> wasapi;

  @ffi.Array.multi([16])
  external ffi.Array<ffi.UnsignedChar> dsound;

  @ffi.UnsignedInt()
  external int winmm;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> alsa;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> pulse;

  @ffi.Int()
  external int jack;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> coreaudio;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> sndio;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> audio4;

  @ffi.Array.multi([64])
  external ffi.Array<ffi.Char> oss;

  @ffi.Int()
  external int aaudio;

  @ffi.UnsignedInt()
  external int opensl;

  @ffi.Array.multi([32])
  external ffi.Array<ffi.Char> webaudio;

  external UnnamedUnion custom;

  @ffi.Int()
  external int nullbackend;
}

final class UnnamedUnion$1 extends ffi.Union {
  external ffi.Pointer<ffi.Pointer<ffi.Float>> f32;

  external ffi.Pointer<ffi.Pointer<ffi.Int>> s16;
}

final class ma_channel_converter extends ffi.Struct {
  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channelsIn;

  @ffi.UnsignedInt()
  external int channelsOut;

  @ffi.UnsignedInt()
  external int mixingMode;

  @ffi.UnsignedInt()
  external int conversionPath;

  external ffi.Pointer<ffi.UnsignedChar> pChannelMapIn;

  external ffi.Pointer<ffi.UnsignedChar> pChannelMapOut;

  external ffi.Pointer<ffi.UnsignedChar> pShuffleTable;

  external UnnamedUnion$1 weights;

  external ffi.Pointer<ffi.Void> _pHeap;

  @ffi.UnsignedInt()
  external int _ownsHeap;
}

/// Resampling
final class ma_linear_resampler_config extends ffi.Struct {
  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.UnsignedInt()
  external int sampleRateIn;

  @ffi.UnsignedInt()
  external int sampleRateOut;

  @ffi.UnsignedInt()
  external int lpfOrder;

  @ffi.Double()
  external double lpfNyquistFactor;
}

final class UnnamedUnion$3 extends ffi.Union {
  external ffi.Pointer<ffi.Float> f32;

  external ffi.Pointer<ffi.Short> s16;
}

final class UnnamedUnion$4 extends ffi.Union {
  external ffi.Pointer<ffi.Float> f32;

  external ffi.Pointer<ffi.Short> s16;
}

final class ma_lpf1 extends ffi.Opaque {}

final class ma_lpf2 extends ffi.Opaque {}

final class ma_lpf extends ffi.Struct {
  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.UnsignedInt()
  external int sampleRate;

  @ffi.UnsignedInt()
  external int lpf1Count;

  @ffi.UnsignedInt()
  external int lpf2Count;

  external ffi.Pointer<ma_lpf1> pLPF1;

  external ffi.Pointer<ma_lpf2> pLPF2;

  external ffi.Pointer<ffi.Void> _pHeap;

  @ffi.UnsignedInt()
  external int _ownsHeap;
}

final class ma_linear_resampler extends ffi.Struct {
  external ma_linear_resampler_config config;

  @ffi.UnsignedInt()
  external int inAdvanceInt;

  @ffi.UnsignedInt()
  external int inAdvanceFrac;

  @ffi.UnsignedInt()
  external int inTimeInt;

  @ffi.UnsignedInt()
  external int inTimeFrac;

  external UnnamedUnion$3 x0;

  external UnnamedUnion$4 x1;

  external ma_lpf lpf;

  external ffi.Pointer<ffi.Void> _pHeap;

  @ffi.UnsignedInt()
  external int _ownsHeap;
}

final class UnnamedUnion$2 extends ffi.Union {
  external ma_linear_resampler linear;
}

final class ma_resampler extends ffi.Struct {
  external ffi.Pointer<ffi.Void> pBackend;

  external ffi.Pointer<ma_resampling_backend_vtable> pBackendVTable;

  external ffi.Pointer<ffi.Void> pBackendUserData;

  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.UnsignedInt()
  external int sampleRateIn;

  @ffi.UnsignedInt()
  external int sampleRateOut;

  external UnnamedUnion$2 state;

  external ffi.Pointer<ffi.Void> _pHeap;

  @ffi.UnsignedInt()
  external int _ownsHeap;
}

final class ma_data_converter extends ffi.Struct {
  @ffi.UnsignedInt()
  external int formatIn;

  @ffi.UnsignedInt()
  external int formatOut;

  @ffi.UnsignedInt()
  external int channelsIn;

  @ffi.UnsignedInt()
  external int channelsOut;

  @ffi.UnsignedInt()
  external int sampleRateIn;

  @ffi.UnsignedInt()
  external int sampleRateOut;

  @ffi.UnsignedInt()
  external int ditherMode;

  @ffi.UnsignedInt()
  external int executionPath;

  external ma_channel_converter channelConverter;

  external ma_resampler resampler;

  @ffi.UnsignedChar()
  external int hasPreFormatConversion;

  @ffi.UnsignedChar()
  external int hasPostFormatConversion;

  @ffi.UnsignedChar()
  external int hasChannelConverter;

  @ffi.UnsignedChar()
  external int hasResampler;

  @ffi.UnsignedChar()
  external int isPassthrough;

  @ffi.UnsignedChar()
  external int _ownsHeap;

  external ffi.Pointer<ffi.Void> _pHeap;
}

final class UnnamedStruct$2 extends ffi.Struct {
  external ffi.Pointer<ma_device_id> pID;

  external ma_device_id id;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> name;

  @ffi.UnsignedInt()
  external int shareMode;

  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.Array.multi([254])
  external ffi.Array<ffi.UnsignedChar> channelMap;

  @ffi.UnsignedInt()
  external int internalFormat;

  @ffi.UnsignedInt()
  external int internalChannels;

  @ffi.UnsignedInt()
  external int internalSampleRate;

  @ffi.Array.multi([254])
  external ffi.Array<ffi.UnsignedChar> internalChannelMap;

  @ffi.UnsignedInt()
  external int internalPeriodSizeInFrames;

  @ffi.UnsignedInt()
  external int internalPeriods;

  @ffi.UnsignedInt()
  external int channelMixMode;

  @ffi.UnsignedInt()
  external int calculateLFEFromSpatialChannels;

  external ma_data_converter converter;

  external ffi.Pointer<ffi.Void> pIntermediaryBuffer;

  @ffi.UnsignedInt()
  external int intermediaryBufferCap;

  @ffi.UnsignedInt()
  external int intermediaryBufferLen;

  external ffi.Pointer<ffi.Void> pInputCache;

  @ffi.UnsignedLongLong()
  external int inputCacheCap;

  @ffi.UnsignedLongLong()
  external int inputCacheConsumed;

  @ffi.UnsignedLongLong()
  external int inputCacheRemaining;
}

final class UnnamedStruct$3 extends ffi.Struct {
  external ffi.Pointer<ma_device_id> pID;

  external ma_device_id id;

  @ffi.Array.multi([256])
  external ffi.Array<ffi.Char> name;

  @ffi.UnsignedInt()
  external int shareMode;

  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.Array.multi([254])
  external ffi.Array<ffi.UnsignedChar> channelMap;

  @ffi.UnsignedInt()
  external int internalFormat;

  @ffi.UnsignedInt()
  external int internalChannels;

  @ffi.UnsignedInt()
  external int internalSampleRate;

  @ffi.Array.multi([254])
  external ffi.Array<ffi.UnsignedChar> internalChannelMap;

  @ffi.UnsignedInt()
  external int internalPeriodSizeInFrames;

  @ffi.UnsignedInt()
  external int internalPeriods;

  @ffi.UnsignedInt()
  external int channelMixMode;

  @ffi.UnsignedInt()
  external int calculateLFEFromSpatialChannels;

  external ma_data_converter converter;

  external ffi.Pointer<ffi.Void> pIntermediaryBuffer;

  @ffi.UnsignedInt()
  external int intermediaryBufferCap;

  @ffi.UnsignedInt()
  external int intermediaryBufferLen;
}

final class UnnamedStruct$4 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int deviceObjectIDPlayback;

  @ffi.UnsignedInt()
  external int deviceObjectIDCapture;

  external ffi.Pointer<ffi.Void> audioUnitPlayback;

  external ffi.Pointer<ffi.Void> audioUnitCapture;

  external ffi.Pointer<ffi.Void> pAudioBufferList;

  @ffi.UnsignedInt()
  external int audioBufferCapInFrames;

  external ma_event stopEvent;

  @ffi.UnsignedInt()
  external int originalPeriodSizeInFrames;

  @ffi.UnsignedInt()
  external int originalPeriodSizeInMilliseconds;

  @ffi.UnsignedInt()
  external int originalPeriods;

  @ffi.UnsignedInt()
  external int originalPerformanceProfile;

  @ffi.UnsignedInt()
  external int isDefaultPlaybackDevice;

  @ffi.UnsignedInt()
  external int isDefaultCaptureDevice;

  @ffi.UnsignedInt()
  external int isSwitchingPlaybackDevice;

  @ffi.UnsignedInt()
  external int isSwitchingCaptureDevice;

  external ffi.Pointer<ffi.Void> pNotificationHandler;
}

final class ma_semaphore extends ffi.Struct {
  @ffi.Int()
  external int value;

  external _opaque_pthread_mutex_t lock;

  external _opaque_pthread_cond_t cond;
}

final class ma_timer extends ffi.Union {
  @ffi.LongLong()
  external int counter;

  @ffi.Double()
  external double counterD;
}

final class ma_atomic_bool32 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int value;
}

final class UnnamedStruct$5 extends ffi.Struct {
  external ffi.Pointer<_opaque_pthread_t> deviceThread;

  external ma_event operationEvent;

  external ma_event operationCompletionEvent;

  external ma_semaphore operationSemaphore;

  @ffi.UnsignedInt()
  external int operation;

  @ffi.UnsignedInt()
  external int operationResult;

  external ma_timer timer;

  @ffi.Double()
  external double priorRunTime;

  @ffi.UnsignedInt()
  external int currentPeriodFramesRemainingPlayback;

  @ffi.UnsignedInt()
  external int currentPeriodFramesRemainingCapture;

  @ffi.UnsignedLongLong()
  external int lastProcessedFramePlayback;

  @ffi.UnsignedLongLong()
  external int lastProcessedFrameCapture;

  external ma_atomic_bool32 isStarted;
}

final class UnnamedUnion$5 extends ffi.Union {
  external UnnamedStruct$4 coreaudio;

  external UnnamedStruct$5 null_device;
}

final class ma_device extends ffi.Struct {
  external ffi.Pointer<ma_context> pContext;

  @ffi.UnsignedInt()
  external int type;

  @ffi.UnsignedInt()
  external int sampleRate;

  external ma_atomic_device_state state;

  external ma_device_data_proc onData;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ma_device_notification> pNotification)
    >
  >
  onNotification;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ma_device> pDevice)>
  >
  onStop;

  external ffi.Pointer<ffi.Void> pUserData;

  external _opaque_pthread_mutex_t startStopLock;

  external ma_event wakeupEvent;

  external ma_event startEvent;

  external ma_event stopEvent;

  external ffi.Pointer<_opaque_pthread_t> thread;

  @ffi.UnsignedInt()
  external int workResult;

  @ffi.UnsignedChar()
  external int isOwnerOfContext;

  @ffi.UnsignedChar()
  external int noPreSilencedOutputBuffer;

  @ffi.UnsignedChar()
  external int noClip;

  @ffi.UnsignedChar()
  external int noDisableDenormals;

  @ffi.UnsignedChar()
  external int noFixedSizedCallback;

  external ma_atomic_float masterVolumeFactor;

  external ma_duplex_rb duplexRB;

  external UnnamedStruct resampling;

  external UnnamedStruct$2 playback;

  external UnnamedStruct$3 capture;

  external UnnamedUnion$5 unnamed;
}

final class UnnamedStruct$6 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int lpfOrder;
}

final class ma_resampler_config extends ffi.Struct {
  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  @ffi.UnsignedInt()
  external int sampleRateIn;

  @ffi.UnsignedInt()
  external int sampleRateOut;

  @ffi.UnsignedInt()
  external int algorithm;

  external ffi.Pointer<ma_resampling_backend_vtable> pBackendVTable;

  external ffi.Pointer<ffi.Void> pBackendUserData;

  external UnnamedStruct$6 linear;
}

final class UnnamedStruct$7 extends ffi.Struct {
  external ffi.Pointer<ma_device_id> pDeviceID;

  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  external ffi.Pointer<ffi.UnsignedChar> pChannelMap;

  @ffi.UnsignedInt()
  external int channelMixMode;

  @ffi.UnsignedInt()
  external int calculateLFEFromSpatialChannels;

  @ffi.UnsignedInt()
  external int shareMode;
}

final class UnnamedStruct$8 extends ffi.Struct {
  external ffi.Pointer<ma_device_id> pDeviceID;

  @ffi.UnsignedInt()
  external int format;

  @ffi.UnsignedInt()
  external int channels;

  external ffi.Pointer<ffi.UnsignedChar> pChannelMap;

  @ffi.UnsignedInt()
  external int channelMixMode;

  @ffi.UnsignedInt()
  external int calculateLFEFromSpatialChannels;

  @ffi.UnsignedInt()
  external int shareMode;
}

final class UnnamedStruct$9 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int usage;

  @ffi.UnsignedChar()
  external int noAutoConvertSRC;

  @ffi.UnsignedChar()
  external int noDefaultQualitySRC;

  @ffi.UnsignedChar()
  external int noAutoStreamRouting;

  @ffi.UnsignedChar()
  external int noHardwareOffloading;

  @ffi.UnsignedInt()
  external int loopbackProcessID;

  @ffi.UnsignedChar()
  external int loopbackProcessExclude;
}

final class UnnamedStruct$10 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int noMMap;

  @ffi.UnsignedInt()
  external int noAutoFormat;

  @ffi.UnsignedInt()
  external int noAutoChannels;

  @ffi.UnsignedInt()
  external int noAutoResample;
}

final class UnnamedStruct$11 extends ffi.Struct {
  external ffi.Pointer<ffi.Char> pStreamNamePlayback;

  external ffi.Pointer<ffi.Char> pStreamNameCapture;

  @ffi.Int()
  external int channelMap;
}

final class UnnamedStruct$12 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int allowNominalSampleRateChange;
}

final class UnnamedStruct$13 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int streamType;

  @ffi.UnsignedInt()
  external int recordingPreset;

  @ffi.UnsignedInt()
  external int enableCompatibilityWorkarounds;
}

final class UnnamedStruct$14 extends ffi.Struct {
  @ffi.UnsignedInt()
  external int usage;

  @ffi.UnsignedInt()
  external int contentType;

  @ffi.UnsignedInt()
  external int inputPreset;

  @ffi.UnsignedInt()
  external int allowedCapturePolicy;

  @ffi.UnsignedInt()
  external int noAutoStartAfterReroute;

  @ffi.UnsignedInt()
  external int enableCompatibilityWorkarounds;

  @ffi.UnsignedInt()
  external int allowSetBufferCapacity;
}

final class ma_device_config extends ffi.Struct {
  @ffi.UnsignedInt()
  external int deviceType;

  @ffi.UnsignedInt()
  external int sampleRate;

  @ffi.UnsignedInt()
  external int periodSizeInFrames;

  @ffi.UnsignedInt()
  external int periodSizeInMilliseconds;

  @ffi.UnsignedInt()
  external int periods;

  @ffi.UnsignedInt()
  external int performanceProfile;

  @ffi.UnsignedChar()
  external int noPreSilencedOutputBuffer;

  @ffi.UnsignedChar()
  external int noClip;

  @ffi.UnsignedChar()
  external int noDisableDenormals;

  @ffi.UnsignedChar()
  external int noFixedSizedCallback;

  external ma_device_data_proc dataCallback;

  external ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(ffi.Pointer<ma_device_notification> pNotification)
    >
  >
  notificationCallback;

  external ffi.Pointer<
    ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ma_device> pDevice)>
  >
  stopCallback;

  external ffi.Pointer<ffi.Void> pUserData;

  external ma_resampler_config resampling;

  external UnnamedStruct$7 playback;

  external UnnamedStruct$8 capture;

  external UnnamedStruct$9 wasapi;

  external UnnamedStruct$10 alsa;

  external UnnamedStruct$11 pulse;

  external UnnamedStruct$12 coreaudio;

  external UnnamedStruct$13 opensl;

  external UnnamedStruct$14 aaudio;
}

const int ma_format_f32 = 5;

const int ma_device_type_capture = 2;
